# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d68b44615154aec025b16cdd6fb63e6968dbcd29ba398c3cba59e0af4e1d3ab8a5814ef2c2b1763b548d3c129b2107fbea74fb0454eba5f1f82bfbcfa815496d

test:
  secret_key_base: d31d6469ea80d2b94e73861aa1ed9f931771882c0f1bfa0e96a28bd749f3db81e4bc224f857fdf1d318c0f9061b84c7b9dc914d1743a3e0e5d1dfd7e0fe43ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
